## Objectives

- Download prices data from an online source

- Load the data into our framework

- Check and Clean data content

- Quick statistical analysis to reveal hidden patterns
- Is it possible to make predictions based on technical
indicators? Stats will answer

#### Importing necessary libraries

In [1]:
import yfinance as yf
import numpy as np
import pandas as pd
import pandas_ta as ta

#### Importing the data from Yahoo Finance

In [2]:
data = pd.DataFrame(yf.download('HINDALCO.ns', period='6mo', interval='1h'))
data.reset_index(inplace=True)  #Converting date time into an index
data.tail()

[*********************100%***********************]  1 of 1 completed

,Datetime,Open,High,Low,Close,Adj Close,Volume
856,2024-09-10 11:15:00+05:30,656.200012,658.200012,654.950012,656.200012,656.200012,272186
857,2024-09-10 12:15:00+05:30,656.000000,661.250000,655.049988,661.000000,661.000000,528491
858,2024-09-10 13:15:00+05:30,661.049988,666.799988,660.849976,663.400024,663.400024,574307
859,2024-09-10 14:15:00+05:30,663.400024,664.849976,657.750000,659.799988,659.799988,806115
860,2024-09-10 15:15:00+05:30,659.750000,660.650024,659.549988,659.750000,659.750000,341050

#### Cleaning the data

In [3]:
data.isna().sum()   #Checking for null values

Datetime     0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [4]:
indexZeroes = data[data['Volume'] == 0].index #Find the index of the data/rows where volume is 0
data.drop(indexZeroes, inplace=True)
data.loc[data["Volume"]==0]

Empty DataFrame
Columns: [Datetime, Open, High, Low, Close, Adj Close, Volume]
Index: []

#### Loading the Pandas Technical Analysis Library

In [5]:
data['ATR'] = ta.atr(close=data['Close'], high=data['High'], low=data['Low'],length=20)
data['RSI'] = ta.rsi(close=data['Close'])
data['Average'] = ta.midprice( high=data['High'], low=data['Low'], length=1)
data['MA40'] = ta.sma(close=data['Close'], length=40)
data['MA80'] = ta.sma(close=data['Close'], length=80)
data['MA160'] = ta.sma(close=data['Close'], length=160)
data

,Datetime,Open,High,Low,Close,Adj Close,Volume,ATR,RSI,Average,MA40,MA80,MA160
1,2024-03-11 10:15:00+05:30,539.950012,539.950012,535.000000,535.599976,535.599976,902516,NaN,NaN,537.475006,NaN,NaN,NaN
2,2024-03-11 11:15:00+05:30,535.250000,539.700012,535.000000,535.799988,535.799988,667804,NaN,NaN,537.350006,NaN,NaN,NaN
3,2024-03-11 12:15:00+05:30,535.900024,539.150024,535.900024,538.099976,538.099976,494737,NaN,NaN,537.525024,NaN,NaN,NaN
4,2024-03-11 13:15:00+05:30,538.200012,538.700012,536.150024,536.849976,536.849976,467037,NaN,NaN,537.425018,NaN,NaN,NaN
5,2024-03-11 14:15:00+05:30,536.900024,537.750000,532.849976,533.200012,533.200012,873473,NaN,NaN,535.299988,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,2024-09-10 11:15:00+05:30,656.200012,658.200012,654.950012,656.200012,656.200012,272186,5.321207,36.802729,656.575012,670.720001,684.582502,660.040000
857,2024-09-10 12:15:00+05:30,656.000000,661.250000,655.049988,661.000000,661.000000,528491,5.365148,44.603546,658.149994,669.695001,684.326252,660.081875
858,2024-09-10 13:15:00+05:30,661.049988,666.799988,660.849976,663.400024,663.400024,574307,5.394391,48.056071,663.824982,669.030002,684.151252,660.179688
859,2024-09-10 14:15:00+05:30,663.400024,664.849976,657.750000,659.799988,659.799988,806115,5.479670,43.660461,661.299988,668.321251,683.830627,660.461250
860,2024-09-10 15:15:00+05:30,659.750000,660.650024,659.549988,659.750000,659.750000,341050,5.260688,43.600826,660.100006,667.700002,683.513126,660.712813